version: "3.8"

services:
  backend:
    image: oussama75/fullstack-backend:latest
    ports:
      - "8081:8080"

  frontend:
    image: oussama75/fullstack-frontend:latest
    ports:
      - "3000:3000"